services:
  grpc:
    container_name: go-grpc-domain
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    command: air -c .air.toml
    volumes:
      - ./src:/go/src
    ports:
      # gRPC Server用のポート設定
      - "50051:50051"
      # gRPC Gateway用のポート設定
      - "8080:8080"
    environment:
      - ENV
      - GRPC_PORT
      - GATEWAY_PORT
    tty: true
    stdin_open: true