// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/usecase/logger/logger.go
//
// Generated by this command:
//
//	mockgen -source=./internal/application/usecase/logger/logger.go -destination=./internal/application/usecase/logger/mock_logger/mock_logger.go
//

// Package mock_logger is a generated GoMock package.
package mock_logger

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(ctx context.Context, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, message)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), ctx, message)
}

// Info mocks base method.
func (m *MockLogger) Info(ctx context.Context, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", ctx, message)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), ctx, message)
}

// Warn mocks base method.
func (m *MockLogger) Warn(ctx context.Context, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", ctx, message)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), ctx, message)
}
